MDM Context Map
atedeg/mdm pull request #111
Opened 2022-07-27 15:08 UTC by vitlinda

This PR introduces the context map of the mdm buoned contexts and its description.
Closes #108

2022-07-29 11:08 UTC, giacomocavalieri commented on docs/_docs/context-map.md
> +This choice was taken as the two concepts above are crucial and every change in the shared kernel must affect every other bounded context.
I'd slightly rephrase this:
```suggestion
There is a *Shared Kernel* among the bounded contexts which contains the definitions for **product** and **cheese type**.
This choice was taken as the two aforementioned concepts are crucial for the cheese factory and a change in any of the definitions must be reflected in all bounded contexts handling these concepts.
In fact, adding a new kind of product involves a series of important domain changes that must be reflected in the code of different bounded contexts: the production, ordering, labelling and stocking processes would need a rehaul to take into account the new kind of product.

By sharing this information among different bounded context it is guaranteed that, whenever a change happens to any of these concepts, all the domains will maintain an up-to-date vision of these concepts.

```

2022-07-29 12:57 UTC, giacomocavalieri approved these changes

2022-07-29 12:57 UTC, ndido98 approved these changes

2022-07-30 08:50 UTC, nicolasfara commented
Yesterday it turned out that `milk-planning` needs an interaction with `stocking` to find out how much product is available to make the milk reorder. No interaction between them appears in the diagram, can you fix it?

2022-07-30 08:51 UTC, nicolasfara requested changes

2022-07-30 08:51 UTC, nicolasfara commented on docs/_docs/context-map.md
> +
Yesterday it turned out that `milk-planning` needs an interaction with `stocking` to find out how much product is available to make the milk reorder. No interaction between them appears in the diagram, can you fix it?

2022-07-30 08:53 UTC, nicolasfara requested changes
In the image there is no interaction between `stocking` and `milk-planning`

2022-07-30 13:24 UTC, nicolasfara approved these changes

2022-07-30 13:24 UTC, merged