DTO utils
atedeg/mdm pull request #139
Opened 2022-08-06 21:19 UTC by giacomocavalieri

This PR adds some (amazingly) magical DTO generation and refactors the restocking DTOs to use autogeneration
![6p4y1f](https://user-images.githubusercontent.com/20598369/183266371-8dfc02e5-06b2-462f-97e8-56c36019c219.jpg)

2022-08-06 21:26 UTC, nicolasfara approved these changes

2022-08-06 21:27 UTC, vitlinda approved these changes

2022-08-06 21:28 UTC, vitlinda requested changes
You must add some tests

2022-08-07 09:59 UTC, nicolasfara approved these changes

2022-08-07 11:57 UTC, vitlinda approved these changes

2022-08-07 11:57 UTC, merged