Add CI workflow
atedeg/mdm pull request #31
Opened 2022-07-16 16:56 UTC by giacomocavalieri

2022-07-16 16:59 UTC, nicolasfara approved these changes

2022-07-17 08:22 UTC, nicolasfara requested changes

2022-07-17 08:22 UTC, nicolasfara commented on .github/workflows/ci.yml
> +  workflow_dispatch:
```suggestion
on:
  push:
    branches:
      - main
      - alpha
      - beta
  pull_request:
  workflow_dispatch:
```

2022-07-17 08:22 UTC, nicolasfara commented on .github/workflows/ci.yml
> +  workflow_dispatch:
Sorry Giacomo, I was wrong when I said we didn't need the trigger on the branch. This way we enable CI only on branches where a release is scheduled.

2022-07-17 08:31 UTC, ndido98 approved these changes

2022-07-17 08:35 UTC, nicolasfara approved these changes

2022-07-17 11:02 UTC, vitlinda approved these changes

2022-07-17 11:04 UTC, merged