Setup documentatio site
atedeg/mdm pull request #5
Opened 2022-05-04 13:06 UTC by nicolasfara

Setup documentation site using [`hugo`](https://gohugo.io/) and the theme [`hugo-theme-learn`](https://github.com/matcornic/hugo-theme-learn).

Close #1

2022-05-04 13:22 UTC, ndido98 requested changes
You probably checked by mistake the `.hugo_build.lock` file

2022-05-04 14:12 UTC, ndido98 approved these changes

2022-05-05 16:35 UTC, vitlinda approved these changes

2022-05-06 06:17 UTC, giacomocavalieri approved these changes

2022-05-06 06:20 UTC, merged